# Generated by Django 2.1.7 on 2024-02-06 02:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20240205_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 2, 5, 23, 57, 54, 794114)),
        ),
    ]
